### ISSUE TITLE
This is the first issue.

### ISSUE THREAD

**Issue by Lancelo-L** [SublimeCT/greasy_monkey_scripts#1]
1. 点击使用当前图片后, 下面那个框里只出现了一个数字, 想要找URL还要去js里翻
![Screenshot_2019-10-02 SpringBoot及SpringCloud版本管理(Gradle版本) - 八九雁来 - CSDN博客](https://user-images.githubusercontent.com/52375886/66050023-029ce000-e55f-11e9-8a93-3b2dc16e6119.png)

2. 自定义图片能不能从本地文件中找, 这样加载可能快一些

3. [ 脚本设置] 那个挂件可以增加一个自动隐藏的复选框, 这样页面看起来就更简洁

**Comment by Lancelo-L** [comment]
如果用户设置了本地的图片, 那么网页的加载顺序, 先加载图片后内容可能更好些

**Comment by SublimeCT** [comment]
1. 这是个 `bug`, 将在下个版本修复
2. 上传本地文件有两种读取方式
    - 从 `localStorage` 中读写, 这种方式有大小限制, 一般是 `5M`, 这种方式只能在当前浏览器中读取, 因为有上述两种限制, 我还没想好要不要写这个功能
    - 上传至第三方图床服务, 这种方式会发起  **跨域请求**(虽然油猴支持跨域, 但需要用户点同意), 并且图床提供商也可能 **不会很稳定**, 所以我也不会开发这个功能
    - 如果有更好的方式可以告诉我 XD
3. 计划增加隐藏设置按钮的选项, 跟随 `go top` 按钮同步显示和隐藏, 同样在下个版本中增加

另外, 针对第二点, 我推荐的解决方案是利用百度的 **自定义背景图片功能** 保存到百度的图片服务器, 我会增加一个新的 `issue` 介绍这种方式
