### ISSUE TITLE
窗口尺寸大小影响美化效果

### ISSUE THREAD

**Issue by EchoGroot** [SublimeCT/greasy_monkey_scripts#11]
你好，请教下这两个问题有解决方法吗？
1、背景图片没有跟随窗口的大小自动拉伸填满，例如我提供的截图中，下半区域没有背景图片
2、能否打开页面时，底部横向滚动栏可以自动滚到中间去

![](https://s3.bmp.ovh/imgs/2022/02/ccc9bdc283afe325.png)

**Comment by SublimeCT** [comment]
已修改, [更新](https://greasyfork.org/zh-CN/scripts/373457) 到最新版试试
