### ISSUE TITLE
文章背景色可以强制修改吗

### ISSUE THREAD

**Issue by 2531** [SublimeCT/greasy_monkey_scripts#15]
如题，目前可以自定义页面背景色，但是文章背景色好像有漏网之鱼，比如[https://jackzhang.blog.csdn.net/article/details/107503663](url)
感谢大佬的付出，解决了多年的强迫症。
![image](https://user-images.githubusercontent.com/35393173/229532995-dd3351f0-7783-41a8-b44b-fc907591091d.png)

**Comment by SublimeCT** [comment]
我这里可以正常显示背景色, 麻烦提供一下 浏览器信息, 再看一下 Console 中是否有报错

**Comment by SublimeCT** [comment]
计划在后续版本中移除深色的样式文件

这好像作者设置的文章皮肤, 设置之后会引入一个深色样式的 [css 文件](https://csdnimg.cn/release/blogv2/dist/pc/themesSkin/skin-years/skin-years-695a31e648.min.css)

**Comment by SublimeCT** [comment]
[v3.0.8](https://github.com/SublimeCT/greasy_monkey_scripts/commit/04738133bf2d29ebfb8611bf3b15a711451d7ff6) 已修改
