### ISSUE TITLE
小东西真别致

### ISSUE THREAD

**Issue by PPQQXX** [SublimeCT/greasy_monkey_scripts#16]
![image](https://github.com/SublimeCT/greasy_monkey_scripts/assets/32433430/644560ed-6c07-407d-aa42-c3d482ea48e8)
这个可以屏蔽掉吗

**Comment by SublimeCT** [comment]
现在无法复现了, 尝试 [更新](https://greasyfork.org/zh-CN/scripts/373457) 到最新版看看有没有问题
