### ISSUE TITLE
CSDN 去广告沉浸阅读模式

### ISSUE THREAD

**Issue by Jagerx** [SublimeCT/greasy_monkey_scripts#3]
通过Greasyfork安装

收藏按钮，点击没反应

**Comment by Jagerx** [comment]
没有登录提示，通过CSDN首页登陆后可以正常收藏

**Comment by SublimeCT** [comment]
记得之前在好多地方点击都会显示这个登录窗口, 对于只想阅读文章的用户来说不太友好, 所以直接 `display: none` 了;
